spring:
  datasource:
    url: jdbc:mysql://localhost:3306/craftpractise
    username: root
    password: 1111

  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        #        dialect: org.hibernate.dialect.Oracle12cDialect
        #        show_sql: true
        format_sql: true

logging.level:
  org.hibernate:
    SQL: debug
#    type: trace